### ISSUE TITLE
flexdashboard 0.5.1 release checklist

### ISSUE THREAD

**Issue by bborgesr** [rstudio/flexdashboard#152]
## Code completion
- [x] Merge #150 

## Testing
- [x] Run the examples in the [website](http://rmarkdown.rstudio.com/flexdashboard/examples.html) under Pandoc 1.9 and 2.0. Note if there is any difference visually. Note if there is any difference in the text diff.
- [x] Put the source code of the examples in the [website](http://rmarkdown.rstudio.com/flexdashboard/examples.html) in an examples directory right here in `flexdashboard` to ease future testing.

## Release checklist (new PR, no code changes there)
- [x] Create a new branch for the release, like `v0.5.1`
- [x] Run `devtoools::check()` and address any possible problems
- [x] Bump version to `0.5.1` in NEWS and DESCRIPTION
- [x] Commit and push to github: https://github.com/rstudio/flexdashboard/pull/161
- [x] Download “clean” copy of package and build source package
- [x] Upload to CRAN
- [x] When accepted to CRAN:
  - [x] create an annotated tag for the "version bump” commit
   ```sh
   git tag -a v0.5.1 -m "flexdashboard 0.5.1 on CRAN"
   git push --tags
   ```
  - [x] create and normal-merge a PR for the new release branch
